import type { Config } from '../../src/shared/types.js';

export function createConfig(overrides: Partial<Config> = {}): Config {
  return {
    discordBotToken: 'test-token',
    discordChannelId: 'channel-1',
    discordServerId: '',
    discordServerName: '',
    discordBossUserId: '111111111111111111',
    ownerIds: ['owner-1'],
    discordAdminId: 'owner-1',
    allowedChannelIds: ['channel-1', 'channel-2'],
    allowedUserIds: ['owner-1'],
    allowedAgentIds: [],
    daemonApiToken: 'daemon-token',
    discordPrefix: '!',
    discordResetCmd: '!reset',
    daemonPort: 18790,
    extensionDir: '/extension',
    geminiPath: 'gemini',
    geminiModel: 'auto',
    geminiTimeoutMs: 300000,
    geminiMaxConcurrent: 3,
    headlessGeminiCliHome: '/extension/.gemini-discord/gemini-cli',
    headlessGeminiCliSettingsFile: '/extension/.gemini-discord/gemini-cli/settings.json',
    geminiCliEnv: undefined,
    conversationHistoryLength: 30,
    promptHistoryMessageLimit: 12,
    promptHistoryCharBudget: 6000,
    streaming: true,
    queueMaxDepth: 20,
    enableDMs: true,
    enableGuests: false,
    enableGuestAttachments: false,
    enableServerMembersIntent: true,
    requireMention: false,
    respondToReplies: false,
    memoryScope: 'channel',
    autoStartDaemon: true,
    useGeminiCliSessions: true,
    geminiSessionBindingScope: 'channel',
    cliIdleTimeoutMs: 300000,
    setupValidationPending: false,
    workflowParentChannelId: '',
    chunkerLimit: 8000,
    geminiAvailableModels: [],
    discordAllowedMentions: ['users'],
    discordPingRepliedUser: true,
    ...overrides,
  };
}
